# Generated by Django 6.0.2 on 2026-02-20 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom de famille')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('subject', models.CharField(choices=[('info', "Demande d'information"), ('inscription', 'Inscription aux cours'), ('college', 'Cours niveau Collège'), ('lycee', 'Cours niveau Lycée'), ('tarifs', 'Tarifs'), ('autre', 'Autre sujet')], max_length=20, verbose_name='Sujet')),
                ('niveau', models.CharField(blank=True, choices=[('', '---'), ('1app', '1ère Année Collège'), ('2app', '2ème Année Collège'), ('3app', '3ème Année Collège'), ('tc', 'Tronc Commun'), ('1bac', '1ère Bac'), ('2bac', '2ème Bac')], max_length=10, null=True, verbose_name='Niveau scolaire')),
                ('message', models.TextField(verbose_name='Message')),
                ('consent', models.BooleanField(default=False, verbose_name='Consentement')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
            ],
        ),
    ]
