# Generated by Django 6.0.2 on 2026-02-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='niveau',
            field=models.CharField(blank=True, choices=[('1app', '1ère Année Collège'), ('2app', '2ème Année Collège'), ('3app', '3ème Année Collège'), ('tc', 'Tronc Commun'), ('1bac', '1ère Bac'), ('2bac', '2ème Bac')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(choices=[('info', "Demande d'information"), ('inscription', 'Inscription aux cours'), ('college', 'Cours niveau Collège'), ('lycee', 'Cours niveau Lycée'), ('tarifs', 'Tarifs'), ('autre', 'Autre sujet')], max_length=20),
        ),
    ]
